/**
 * Write Headers Hook
 * Adds standard headers to new files being created
 * Part of OrchestKit Claude Plugin
 */

import type { HookInput, HookResult } from '../../types.js';
import { outputSilentSuccess, logHook } from '../../lib/common.js';
import { existsSync } from 'node:fs';
import { extname } from 'node:path';

/**
 * Get current date in YYYY-MM-DD format
 */
function getCurrentDate(): string {
  return new Date().toISOString().split('T')[0];
}

/**
 * Add header based on file type
 */
function addHeader(ext: string, content: string): string {
  const date = getCurrentDate();

  switch (ext.toLowerCase()) {
    case 'py':
      return `# Generated by OrchestKit Claude Plugin
# Created: ${date}

${content}`;

    case 'js':
    case 'ts':
      return `// Generated by OrchestKit Claude Plugin
// Created: ${date}

${content}`;

    case 'sh': {
      // For shell scripts, add after shebang if present
      if (content.startsWith('#!/')) {
        const firstNewline = content.indexOf('\n');
        const shebang = content.slice(0, firstNewline);
        const rest = content.slice(firstNewline + 1);
        return `${shebang}
# Generated by OrchestKit Claude Plugin
# Created: ${date}

${rest}`;
      }
      return `#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: ${date}

${content}`;
    }

    case 'sql':
      return `-- Generated by OrchestKit Claude Plugin
-- Created: ${date}

${content}`;

    case 'html':
    case 'xml':
      return `<!-- Generated by OrchestKit Claude Plugin - ${date} -->

${content}`;

    case 'css':
    case 'scss':
    case 'sass':
      return `/* Generated by OrchestKit Claude Plugin - ${date} */

${content}`;

    case 'yaml':
    case 'yml':
      return `# Generated by OrchestKit Claude Plugin
# Created: ${date}

${content}`;

    case 'json':
      // Don't add header for JSON (would break JSON format)
      return content;

    default:
      // No header for unknown file types
      return content;
  }
}

/**
 * Create result with updated input
 */
function createUpdatedInputResult(filePath: string, content: string): HookResult {
  return {
    continue: true,
    suppressOutput: true,
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'allow',
      // Note: updatedInput is not in the HookSpecificOutput type
      // but is used by CC for input modification
    },
  } as HookResult;
}

/**
 * Write headers hook - adds headers to new files
 */
export function writeHeaders(input: HookInput): HookResult {
  const toolName = input.tool_name || '';
  const filePath = input.tool_input.file_path || '';
  const content = input.tool_input.content || '';

  // Only process Write tool (not Edit - those are existing files)
  if (toolName !== 'Write') {
    return outputSilentSuccess();
  }

  // Check if file already exists (skip header if it does)
  if (existsSync(filePath)) {
    return outputSilentSuccess();
  }

  // Get file extension
  const ext = extname(filePath).replace('.', '');

  // Skip if content already contains OrchestKit header
  if (content.includes('OrchestKit')) {
    logHook('write-headers', `Skipping header for ${filePath} (already has OrchestKit marker)`);
    return outputSilentSuccess();
  }

  // Add header
  const updatedContent = addHeader(ext, content);
  const headerAdded = updatedContent !== content;

  if (headerAdded) {
    logHook('write-headers', `Added header to ${filePath}`);
  }

  // Return result with updated input
  // Note: This uses the CC input modification pattern
  return {
    continue: true,
    suppressOutput: true,
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'allow',
    },
  };
}
