"""
Consumer Contract Test Template
Generated by OrchestKit contract-testing skill
"""

import pytest
from pact import Consumer, Provider, Like, EachLike, Term, Format


# =============================================================================
# Pact Configuration
# =============================================================================

CONSUMER_NAME = "MyConsumer"  # TODO: Replace with your consumer name
PROVIDER_NAME = "MyProvider"  # TODO: Replace with your provider name


@pytest.fixture(scope="module")
def pact():
    """Configure and start Pact mock server."""
    pact = Consumer(CONSUMER_NAME).has_pact_with(
        Provider(PROVIDER_NAME),
        pact_dir="./pacts",
        log_dir="./logs",
    )
    pact.start_service()
    yield pact
    pact.stop_service()
    pact.verify()


# =============================================================================
# GET Request Contract
# =============================================================================


def test_get_resource(pact):
    """Test GET request contract."""
    expected_response = {
        "id": Like("resource-123"),
        "name": Like("Resource Name"),
        "status": Term(r"active|inactive|pending", "active"),
        "created_at": Format().iso_8601_datetime(),
        "metadata": {
            "version": Like(1),
            "tags": EachLike("tag-value", minimum=0),
        },
    }

    (
        pact
        .given("resource resource-123 exists")
        .upon_receiving("a request to get resource resource-123")
        .with_request(
            method="GET",
            path="/api/resources/resource-123",
            headers={"Authorization": Like("Bearer token")},
        )
        .will_respond_with(
            status=200,
            headers={"Content-Type": "application/json"},
            body=expected_response,
        )
    )

    with pact:
        # TODO: Replace with your actual client call
        # client = MyClient(base_url=pact.uri)
        # result = client.get_resource("resource-123")
        # assert result.id == "resource-123"
        pass


# =============================================================================
# POST Request Contract
# =============================================================================


def test_create_resource(pact):
    """Test POST request contract."""
    request_body = {
        "name": "New Resource",
        "type": "standard",
    }

    expected_response = {
        "id": Like("resource-new"),
        "name": "New Resource",
        "type": "standard",
        "status": "pending",
        "created_at": Format().iso_8601_datetime(),
    }

    (
        pact
        .given("user is authenticated")
        .upon_receiving("a request to create a resource")
        .with_request(
            method="POST",
            path="/api/resources",
            headers={
                "Content-Type": "application/json",
                "Authorization": Like("Bearer token"),
            },
            body=request_body,
        )
        .will_respond_with(
            status=201,
            headers={"Content-Type": "application/json"},
            body=expected_response,
        )
    )

    with pact:
        # TODO: Replace with your actual client call
        pass


# =============================================================================
# List Request Contract
# =============================================================================


def test_list_resources(pact):
    """Test paginated list request contract."""
    expected_response = {
        "items": EachLike(
            {
                "id": Like("resource-1"),
                "name": Like("Resource"),
                "status": Term(r"active|inactive", "active"),
            },
            minimum=1,
        ),
        "total": Like(100),
        "page": Like(1),
        "page_size": Like(20),
        "has_more": Like(True),
    }

    (
        pact
        .given("multiple resources exist")
        .upon_receiving("a request to list resources")
        .with_request(
            method="GET",
            path="/api/resources",
            query={"page": "1", "page_size": "20"},
            headers={"Authorization": Like("Bearer token")},
        )
        .will_respond_with(
            status=200,
            headers={"Content-Type": "application/json"},
            body=expected_response,
        )
    )

    with pact:
        # TODO: Replace with your actual client call
        pass


# =============================================================================
# Error Response Contracts
# =============================================================================


def test_resource_not_found(pact):
    """Test 404 response contract."""
    (
        pact
        .given("resource unknown-id does not exist")
        .upon_receiving("a request for non-existent resource")
        .with_request(
            method="GET",
            path="/api/resources/unknown-id",
            headers={"Authorization": Like("Bearer token")},
        )
        .will_respond_with(
            status=404,
            headers={"Content-Type": "application/json"},
            body={
                "error": "not_found",
                "message": Like("Resource not found"),
            },
        )
    )

    with pact:
        # TODO: Test error handling
        # with pytest.raises(ResourceNotFoundError):
        #     client.get_resource("unknown-id")
        pass


def test_validation_error(pact):
    """Test 422 validation error contract."""
    (
        pact
        .given("validation is enabled")
        .upon_receiving("a request with invalid data")
        .with_request(
            method="POST",
            path="/api/resources",
            headers={
                "Content-Type": "application/json",
                "Authorization": Like("Bearer token"),
            },
            body={"name": ""},  # Invalid: empty name
        )
        .will_respond_with(
            status=422,
            headers={"Content-Type": "application/json"},
            body={
                "errors": EachLike(
                    {
                        "field": Like("name"),
                        "message": Like("Field is required"),
                    },
                    minimum=1,
                ),
            },
        )
    )

    with pact:
        # TODO: Test validation error handling
        pass
