#!/bin/bash
# write-headers.sh - Adds standard headers to new files being created
# Part of OrchestKit Claude Plugin v4.4.2

set -euo pipefail

# Read input from stdin
INPUT=$(cat)

# Extract parameters (using correct Claude Code field names)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')
CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // ""')
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // "unknown"')
ORIGINAL_CONTENT="$CONTENT"

# Only process Write tool (not Edit - those are existing files)
if [[ "$TOOL_NAME" != "Write" ]]; then
  jq -n \
    --argjson params "$(echo "$INPUT" | jq '.tool_input')" \
    '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "allow",
        updatedInput: $params
      }
    ,"continue":true,"suppressOutput":true}'
  exit 0
fi

# Check if file already exists (skip header if it does)
if [[ -f "$FILE_PATH" ]]; then
  jq -n \
    --argjson params "$(echo "$INPUT" | jq '.tool_input')" \
    '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "allow",
        updatedInput: $params
      }
    ,"continue":true,"suppressOutput":true}'
  exit 0
fi

# Get file extension
EXTENSION="${FILE_PATH##*.}"

# Function to add header based on file type
add_header() {
  local ext="$1"
  local content="$2"
  local header=""

  case "$ext" in
    py)
      header="# Generated by OrchestKit Claude Plugin
# Created: $(date +%Y-%m-%d)

"
      ;;
    js|ts)
      header="// Generated by OrchestKit Claude Plugin
// Created: $(date +%Y-%m-%d)

"
      ;;
    sh)
      # For shell scripts, add after shebang if present
      if [[ "$content" == "#!/"* ]]; then
        local shebang=$(echo "$content" | head -n1)
        local rest=$(echo "$content" | tail -n +2)
        header="$shebang
# Generated by OrchestKit Claude Plugin
# Created: $(date +%Y-%m-%d)

$rest"
        echo "$header"
        return
      else
        header="#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: $(date +%Y-%m-%d)

"
      fi
      ;;
    sql)
      header="-- Generated by OrchestKit Claude Plugin
-- Created: $(date +%Y-%m-%d)

"
      ;;
    html|xml)
      header="<!-- Generated by OrchestKit Claude Plugin - $(date +%Y-%m-%d) -->

"
      ;;
    css|scss|sass)
      header="/* Generated by OrchestKit Claude Plugin - $(date +%Y-%m-%d) */

"
      ;;
    yaml|yml)
      header="# Generated by OrchestKit Claude Plugin
# Created: $(date +%Y-%m-%d)

"
      ;;
    json)
      # For JSON, don't add header (would break JSON format)
      echo "$content"
      return
      ;;
    *)
      # No header for unknown file types
      echo "$content"
      return
      ;;
  esac

  echo "${header}${content}"
}

# Add header if content doesn't already contain "OrchestKit"
if [[ "$CONTENT" != *"OrchestKit"* ]]; then
  UPDATED_CONTENT=$(add_header "$EXTENSION" "$CONTENT")
  HEADER_ADDED="true"
  # Silent operation - log to file if needed instead of stderr (causes "hook error" display)
else
  UPDATED_CONTENT="$CONTENT"
  HEADER_ADDED="false"
fi

# Output decision with systemMessage for user visibility

jq -n \
  --arg file_path "$FILE_PATH" \
  --arg content "$UPDATED_CONTENT" \
  '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "allow",
      updatedInput: {
        file_path: $file_path,
        content: $content
      }
    }
  ,"continue":true,"suppressOutput":true}'
